version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    reviewers:
      - patrick.zippenfenig
    allow:
      - dependency-type: direct
    commit-message:
      prefix: "fix: "
    groups:
      semantic:
        patterns:
          - "@semantic-release/*"
          - "semantic-release"
          - "semantic-release-pypi"
          - "conventional-changelog-conventionalcommits"
          - "typescript"
          - "gradle-semantic-release-plugin"
          - "@droidsolutions-oss/semantic-release-nuget"
